export const categories = [
  { name: "Пицца" },
  { name: "Роллы" },
  { name: "Салаты" },
  { name: "Морепродукты" },
  { name: "BBQ" },
];

export const products = [
  {
    name: "Цезарь",
    categories: "Салат",
    price: 500,
    quantity: 10,
    availability: false,
    popular: false,
  },
  {
    name: "Оливье",
    categories: "Салат",
    price: 400,
    quantity: 10,
    availability: true,
    popular: true,
  },
  {
    name: "Греческий",
    categories: "Салат",
    price: 600,
    quantity: 10,
    availability: true,
    popular: false,
  },
  {
    name: "Борщ",
    categories: "Супы",
    price: 500,
    quantity: 10,
    availability: true,
    popular: false,
  },
  {
    name: "Уха",
    categories: "Супы",
    price: 500,
    quantity: 10,
    availability: true,
    popular: false,
  },
  {
    name: "Харчо",
    categories: "Супы",
    price: 500,
    quantity: 10,
    availability: true,
    popular: false,
  },
  {
    name: "Стейк",
    categories: "Второе",
    price: 1500,
    quantity: 10,
    availability: true,
    popular: false,
  },
  {
    name: "Шашлык",
    categories: "Второе",
    price: 1200,
    quantity: 10,
    availability: true,
    popular: false,
  },
  {
    name: "Азу",
    categories: "Второе",
    price: 900,
    quantity: 10,
    availability: true,
    popular: false,
  },
  {
    name: "4 сыра",
    categories: "Пицца",
    price: 1000,
    quantity: 10,
    availability: true,
    popular: false,
  },
  {
    name: "Мясная",
    categories: "Пицца",
    price: 1300,
    quantity: 10,
    availability: true,
    popular: false,
  },
  {
    name: "Грибная",
    categories: "Пицца",
    price: 1000,
    quantity: 10,
    availability: true,
    popular: false,
  },
];

export const tableHeaderCategories = [
  { name: "Наименование", code: "name", type: "str" },
  { name: "В наличии", code: "availability", type: "checkbox" },
];

export const tableHeaderMenu = [
  { name: "Наименование", code: "name", type: "str" },
  { name: "Категория", code: "categories", type: "str" },
  { name: "Цена", code: "price", type: "str" },
  { name: "В наличии", code: "availability", type: "checkbox" },
  { name: "Самовывоз", code: "pickup", type: "checkbox" },
  { name: "Доставка", code: "delivery", type: "checkbox" },
  { name: "Зал", code: "hall", type: "checkbox" },
  { name: "Популярное", code: "popular", type: "checkbox" },
];
